baseURL = 'https://dunamismax.com/'
languageCode = 'en-us'
title = 'dunamismax.com'
theme = 'hugo-paper'

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[params]
  # color style options: linen, wheat, gray, light
  color = 'linen'

  # Social & identity
  name = 'DunamisMax'
  bio = 'IT Director learning software engineering with Rust'

  # Social links
  github = 'DunamisMax'
  bluesky = 'dunamismax.bsky.social'

  # Home page avatar
  avatar = '/images/avatar.png'

  # Misc settings
  disablePostNavigation = true
  monoDarkIcon = true
  math = true
  localKatex = false
  favicon = '/favicon.ico'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
